server:
  port: 8084
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true
    fetch-registry: true
    
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/empMicroDb?createDatabaseIfNotExist=true
    username: root
    password: Jan14@1948
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    properties: 
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: update
        format_sql: true
        use_sql_comments: true
