spring:
  cloud:
    config:
      uri: http://localhost:8080
      enabled: true
      
  application:
    name: discovery-server

server:
  port: 8081
  
eureka:
  instance:
    hostname: 192.168.0.104
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
