server:
  port: 8082
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true
    
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/empMicroDb?createDatabaseIfNotExist=true
    username: root
    password: 12345
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    properties: 
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: update
        format_sql: true
        use_sql_comments: true
        
management:
  endpoints:
    web: 
      exposure:
        include: '*'
        
welcome:
  message: Hello ! This Is Employee Service
